#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

if [ $path = "/" ]
then
    ynh_config_add --template="config_domain.json" --destination="$install_dir/config.json"
    ynh_app_setting_set --key=adminurl --value=https://$domain/stats
else
    ynh_config_add --template="config_path.json" --destination="$install_dir/config.json"
    ynh_app_setting_set --key=adminurl --value=https://$domain$path/stats
fi

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add "$app" --description="virtual tabletop games" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL VIRTUALTABLETOP
#=================================================
ynh_script_progression "Building $app..."

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app npm install
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log" --wait_until="Listening on"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
