#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="config.json"

chmod 750 "$install_dir"
chown -R $app:$app "$install_dir"

#=================================================
# ADMIN PATH URL RECONFIGURATION
#=================================================


ynh_script_progression "Updating admin path and url..."

if [ $path = "/" ]
then
    ynh_app_setting_set --key=adminurl --value=https://$domain/stats
else

    ynh_app_setting_set --key=adminurl --value=https://$domain$path/stats
fi

ynh_app_setting_set --key=adminpath --value=stats

ynh_write_var_in_file --file="$install_dir/config.json" --key="adminURL" --value="/stats"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add "$app" --description="virtual tabletop games" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL VIRTUALTABLETOP
#=================================================
ynh_script_progression "Building $app..."

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app npm install
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log" --wait_until="Listening on"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Upgrade of $app completed"
